spring:
  datasource:
    url: jdbc:h2:mem:swd2024
    username: sdw2024
    password: sdw2024
  jpa:
    show-sql: true
    open-in-value: false
    hibernate:
      ddl-auto: create # validate| update | create | creat-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
    web-allow-others: false